version: '3.8'

services:
  key-generator:
    image: key-generator:latest
    container_name: key-generator
    ports:
      - "5001:5001"
    volumes:
      - ./keys:/app/keys
    restart: unless-stopped

