apiVersion: v1
kind: PersistentVolume
metadata:
  name: key-generator-pv
  namespace: key-generator
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/key-generator
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - your-node-name  # Replace with your Proxmox node name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: key-generator-pvc
  namespace: key-generator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
