apiVersion: v1
kind: Service
metadata:
  name: key-generator
  namespace: key-generator
  labels:
    app: key-generator
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30501
    protocol: TCP
    name: http
  selector:
    app: key-generator
