name: Reusable Setup Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        type: string
        default: '3.12'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install GPG
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
    
    - name: Create test directories
      run: |
        mkdir -p keys/ssh keys/rsa keys/pgp
        chmod -R 700 keys
