name: Security Checks

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly security scan

permissions:
  contents: read
  security-events: write

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: '3.12'

  security-scan:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt bandit safety
    
    - name: Create test directories
      run: |
        mkdir -p keys/ssh keys/rsa keys/pgp
        chmod -R 700 keys
    
    - name: Run Bandit security checks
      run: |
        bandit -r . -c .bandit.yaml -x B101,B108 -f json -o bandit-results.json
    
    - name: Run Safety dependency check
      run: |
        safety check --full-report || true  # Continue workflow even if vulnerabilities are found
    
    - name: Analyze Safety Report
      run: |
        safety check --output json > safety-report.json
        cat safety-report.json
    
    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-security-report
        path: bandit-results.json
