name: Test Workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: read
  packages: write

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: '3.12'

  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt bandit pytest pytest-cov requests
    
    - name: Create test directories
      run: |
        mkdir -p keys/ssh keys/rsa keys/pgp
        chmod -R 700 keys
    
    - name: Run Bandit security checks
      run: bandit -r . -c .bandit.yaml -x B101,B108
    
    - name: Run unit tests with coverage
      env:
        GNUPGHOME: ${{ github.workspace }}/keys/gpg
        KEY_STORAGE_PATH: ${{ github.workspace }}/keys
      run: pytest tests/unit/ --cov=. --cov-report=xml -v
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest requests
    
    - name: Create test directories
      run: |
        mkdir -p keys/ssh keys/rsa keys/pgp
        chmod -R 700 keys
    
    - name: Start application
      env:
        FLASK_DEBUG: 0
        PORT: 5001
        GNUPGHOME: ${{ github.workspace }}/keys/gpg
        KEY_STORAGE_PATH: ${{ github.workspace }}/keys
      run: |
        python app.py &
        echo $! > app.pid
        sleep 5  # Wait for the application to start
    
    - name: Run integration tests
      env:
        GNUPGHOME: ${{ github.workspace }}/keys/gpg
        KEY_STORAGE_PATH: ${{ github.workspace }}/keys
      run: pytest tests/integration/ -v
    
    - name: Cleanup
      if: always()
      run: |
        if [ -f app.pid ]; then
          kill $(cat app.pid) || true
          rm app.pid
        fi
        rm -rf keys
