name: Function Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg openssh-client libffi-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-sugar
        pip install -r requirements.txt
    
    - name: Create test directories
      run: |
        mkdir -p tests/keys/{ssh,rsa,pgp}
        mkdir -p tests/keys/.gnupg
        chmod 700 tests/keys/.gnupg
    
    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}
        KEY_STORAGE_PATH: ${{ github.workspace }}/tests/keys
        GNUPGHOME: ${{ github.workspace }}/tests/keys/.gnupg
      run: |
        python -m pytest tests/ -v --cov=./ --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
